# ServiceAccount used for fastapi-template.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: <SERVICE_ACCOUNT_NAME> # Dedicated ServiceAccount for the workload
  namespace: <NAMESPACE> # Example: default
automountServiceAccountToken: false # Disable API access

---